title: Alauda Cache Service for Redis OSS
logoText: Alauda Cache Service for Redis OSS
lang: zh
api:
  crds:
    - docs/shared/crds/*.yaml
  openapis:
    - docs/shared/openapis/*.json
permission:
  functionresources:
    - docs/shared/functionresources/*.yaml
  roletemplates:
    - docs/shared/roletemplates/*.yaml
