apiVersion: builds.katanomi.dev/v1alpha1
kind: Build
spec:
  runTemplate:
    spec:
      timeouts:
        pipeline: 1h
      workspaces:
        - name: source
          volumeClaimTemplate:
            spec:
              storageClassName: topolvm
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Gi
        - name: cache
          persistentVolumeClaim:
            claimName: build-cache
          subPath: yarn_cache
      taskRunSpecs:
        - pipelineTaskName: build-online-docs
          taskPodTemplate:
            env:
              - name: JIRA_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: idpbot-for-jira
                    key: username
              - name: JIRA_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: idpbot-for-jira
                    key: password
        - pipelineTaskName: build-offline-docs
          taskPodTemplate:
            env:
              - name: JIRA_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: idpbot-for-jira
                    key: username
              - name: JIRA_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: idpbot-for-jira
                    key: password
        - pipelineTaskName: export-docs
          taskPodTemplate:
            env:
              - name: JIRA_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: idpbot-for-jira
                    key: username
              - name: JIRA_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: idpbot-for-jira
                    key: password
  workspaces:
    - name: source
    - name: cache
  tasks:
    - name: install-dependencies
      retries: 2
      workspaces:
        - name: source
          workspace: source
        - name: cache
          workspace: cache
      taskSpec:
        steps:
          - image: build-harbor.alauda.cn/frontend/playwright-runner:doom
            name: install
            imagePullPolicy: Always
            workingDir: $(workspaces.source.path)
            resources:
              requests:
                cpu: 2
                memory: 4Gi
              limits:
                cpu: 4
                memory: 4Gi
            script: |
              # set -x
              export COREPACK_NPM_REGISTRY=https://edge-nexus.alauda.cn/repository/cnpm
              export YARN_GLOBAL_FOLDER=/workspace/yarn_cache/global
              yarn config set npmRegistryServer https://edge-nexus.alauda.cn/repository/cnpm
              yarn --immutable
              git reset --hard
    - name: modify-build-config
      runAfter:
        - install-dependencies
      workspaces:
        - name: source
          workspace: source
      params:
        - name: branch
          value: $(build.git.branch.name)
      taskSpec:
        steps:
          - image: build-harbor.alauda.cn/idp/docs-ops:main
            name: modify-build-config
            imagePullPolicy: Always
            workingDir: $(workspaces.source.path)
            command:
            - xonsh
            - /apps/modify_build_config.xsh
            args:
            - --base=redis
            - --branch=$(params.branch)
    - name: build-online-docs
      runAfter:
        - modify-build-config
      retries: 2
      workspaces:
        - name: source
          workspace: source
      params:
        - name: branch
          value: $(build.git.branch.name)
      taskSpec:
        steps:
          - image: build-harbor.alauda.cn/frontend/playwright-runner:doom
            name: build
            imagePullPolicy: Always
            workingDir: $(workspaces.source.path)
            env:
              - name: NODE_OPTIONS
                value: "--max_old_space_size=14336"
            resources:
              requests:
                cpu: 2
                memory: 4Gi
              limits:
                cpu: 4
                memory: 8Gi
            script: |
              # set -x
              rm -rf dist/redis/$(params.branch)
              yarn build-online
    - name: build-offline-docs
      runAfter:
        - build-online-docs
      retries: 2
      workspaces:
        - name: source
          workspace: source
      taskSpec:
        steps:
          - image: build-harbor.alauda.cn/frontend/playwright-runner:doom
            name: build
            imagePullPolicy: Always
            workingDir: $(workspaces.source.path)
            env:
              - name: NODE_OPTIONS
                value: "--max_old_space_size=14336"
            resources:
              requests:
                cpu: 2
                memory: 4Gi
              limits:
                cpu: 4
                memory: 8Gi
            script: |
              # set -x
              rm -rf dist/redis/unversioned
              yarn build-offline
    - name: export-docs
      runAfter:
        - build-offline-docs
      retries: 2
      workspaces:
        - name: source
          workspace: source
      when:
        - input: $(build.git.branch.name)
          operator: notin
          values:
            - master
            - main
      taskSpec:
        steps:
          - image: build-harbor.alauda.cn/frontend/playwright-runner:doom
            name: build
            imagePullPolicy: Always
            workingDir: $(workspaces.source.path)
            env:
              - name: NODE_OPTIONS
                value: "--max_old_space_size=14336"
            resources:
              requests:
                cpu: 2
                memory: 4Gi
              limits:
                cpu: 4
                memory: 8Gi
            script: |
              # set -x
              yarn export
    - name: upload-artifacts
      runAfter:
        - build-online-docs
        - build-offline-docs
        - export-docs
      retries: 2
      workspaces:
        - name: source
          workspace: source
      params:
        - name: branch
          value: $(build.git.branch.name)
        - name: commit
          value: $(build.git.lastCommit.id)
      taskSpec:
        steps:
          - image: build-harbor.alauda.cn/idp/docs-ops:main
            name: upload-artifacts
            imagePullPolicy: Always
            workingDir: $(workspaces.source.path)
            env:
              - name: MINIO_URL
                valueFrom:
                  secretKeyRef:
                    name: product-docs-minio-credentials
                    key: url
              - name: MINIO_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: product-docs-minio-credentials
                    key: access-key
              - name: MINIO_SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: product-docs-minio-credentials
                    key: secret-key
              - name: MINIO_BUCKET
                valueFrom:
                  secretKeyRef:
                    name: product-docs-minio-credentials
                    key: bucket
            command:
            - xonsh
            - /apps/upload_doc_artifacts.xsh
            args:
            - --base=redis
            - --branch=$(params.branch)
            - --commit=$(params.commit)