apiVersion: builds.katanomi.dev/v1alpha1
kind: Build
spec:
  runTemplate:
    spec:
      timeouts:
        pipeline: 1h
      workspaces:
        - name: source
          volumeClaimTemplate:
            spec:
              storageClassName: topolvm
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Gi
        - name: cache
          persistentVolumeClaim:
            claimName: build-cache
          subPath: yarn_cache
      taskRunSpecs:
        - pipelineTaskName: build-docs
          taskPodTemplate:
            env:
              - name: JIRA_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: idpbot-for-jira
                    key: username
              - name: JIRA_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: idpbot-for-jira
                    key: password
  workspaces:
    - name: source
    - name: cache
  tasks:
    - name: install-dependencies
      retries: 2
      workspaces:
        - name: source
          workspace: source
        - name: cache
          workspace: cache
      taskSpec:
        steps:
          - image: build-harbor.alauda.cn/frontend/playwright-runner:doom
            name: install
            imagePullPolicy: Always
            workingDir: $(workspaces.source.path)
            resources:
              requests:
                cpu: 2
                memory: 4Gi
              limits:
                cpu: 4
                memory: 4Gi
            script: |
              # set -x
              export COREPACK_NPM_REGISTRY=https://edge-nexus.alauda.cn/repository/cnpm
              export YARN_GLOBAL_FOLDER=/workspace/yarn_cache/global
              yarn config set npmRegistryServer https://edge-nexus.alauda.cn/repository/cnpm
              yarn --immutable
              git reset --hard
    - name: modify-build-config
      runAfter:
        - install-dependencies
      workspaces:
        - name: source
          workspace: source
      params:
        - name: branch
          value: $(build.git.branch.name)
      taskSpec:
        steps:
          - image: build-harbor.alauda.cn/idp/docs-ops:main
            name: modify-build-config
            imagePullPolicy: Always
            workingDir: $(workspaces.source.path)
            command:
            - xonsh
            - /apps/modify_build_config.xsh
            args:
            - --base=redis
            - --branch=$(params.branch)
    - name: build-docs
      runAfter:
        - modify-build-config
      retries: 2
      workspaces:
        - name: source
          workspace: source
      params:
        - name: branch
          value: $(build.git.branch.name)
      taskSpec:
        steps:
          - image: build-harbor.alauda.cn/frontend/playwright-runner:doom
            name: build
            imagePullPolicy: Always
            workingDir: $(workspaces.source.path)
            env:
              - name: NODE_OPTIONS
                value: "--max_old_space_size=14336"
            resources:
              requests:
                cpu: 2
                memory: 4Gi
              limits:
                cpu: 4
                memory: 8Gi
            script: |
              # set -x
              yarn build-online